### ISSUE TITLE
HoverFly Goin Down while using Diff mode

### ISSUE THREAD

**Issue by chaitanya2829** [arquillian/arquillian-organization#38] opened 2019-03-07 18:26 UTC
Hi Team,

I was using the diff mode in my hoverfly , and want to check the difference in responses in simulation against the real service , while i was doing the test in my machine - hoverfly is going down immediately when i use the diff mode.

Steps to replicate:

1)Captured the responses and altered the responses ( changed the data )
2) Now changed the mode to diff, and tried hitting the service...but hoverfly is going down immediately.

Can you please replicate the above steps and let me know the work around .Let me know if you need further details.

**Comment by JohnFDavenport** [comment] 2019-03-08 10:01
Duplicate of https://github.com/SpectoLabs/hoverfly/issues/823

**Comment by bartoszmajsak** [comment] 2019-03-25 10:33
Closing in favor of SpectoLabs/hoverfly#823

**Closed as completed by bartoszmajsak** 2019-03-25 10:33 UTC
